INSERT INTO CLIP_USER(USER_ID,USER_NAME) VALUES(1,'Everardo Lopez');
INSERT INTO CLIP_USER(USER_ID,USER_NAME) VALUES(2,'Juan Perez');
INSERT INTO CLIP_USER(USER_ID,USER_NAME) VALUES(3,'Ricardo Martinez');
INSERT INTO CLIP_USER(USER_ID,USER_NAME) VALUES(4,'Manuel Ramos');
INSERT INTO CLIP_USER(USER_ID,USER_NAME) VALUES(5,'Carmen Hernandez');