CREATE TABLE CLIP_USER(
    USER_ID INT  PRIMARY KEY,
    USER_NAME VARCHAR(128) NOT NULL
);

CREATE TABLE CLIP_DISBURSEMENT(
    DISBURSEMENT_ID INT PRIMARY KEY,
    DISBURSEMENT_AMOUNT FLOAT NOT NULL,
    USER_ID INT NOT NULL,
    DISBURSEMENT_DATE DATE NOT NULL
);

CREATE TABLE CLIP_TRANSACTION(
    TRANSACTION_ID INT   PRIMARY KEY,
    USER_ID INT NOT NULL,
    AMOUNT FLOAT NOT NULL,
    CARD_DATA VARCHAR(128) NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    DISBURSEMENT_ID INT
);

ALTER TABLE CLIP_DISBURSEMENT ADD FOREIGN KEY (USER_ID) REFERENCES CLIP_USER(USER_ID);
CREATE SEQUENCE DISBURSEMENT_SEQUENCE_ID START WITH (select max(DISBURSEMENT_ID) + 1 from CLIP_DISBURSEMENT);

ALTER TABLE CLIP_TRANSACTION ADD FOREIGN KEY (USER_ID) REFERENCES CLIP_USER(USER_ID);
ALTER TABLE CLIP_TRANSACTION ADD FOREIGN KEY (DISBURSEMENT_ID) REFERENCES CLIP_DISBURSEMENT(DISBURSEMENT_ID);
CREATE SEQUENCE TRANSACTION_SEQUENCE_ID START WITH (select max(TRANSACTION_ID) + 1 from CLIP_TRANSACTION);

