CREATE TABLE CLIP_USER(
    USER_ID INT  PRIMARY KEY,
    USER_NAME VARCHAR(128) NOT NULL
);

CREATE TABLE CLIP_TRANSACTION(
    TRANSACTION_ID INT   PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    AMOUNT FLOAT NOT NULL,
    CARD_DATA VARCHAR(128) NOT NULL,
    TRANSACTION_DATE DATE NOT NULL
);

ALTER TABLE CLIP_TRANSACTION ADD FOREIGN KEY (USER_ID) REFERENCES CLIP_USER(USER_ID);
CREATE SEQUENCE TRANSACTION_SEQUENCE_ID START WITH (select max(TRANSACTION_ID) + 1 from CLIP_TRANSACTION);